// Generated by Pixel Designer
use crate::pixel_graphics::PixelGraphics;

pub fn render_ui(pg: &mut PixelGraphics) {
    pg.draw_table_view(60, 160, 450, "System Log", 285);
    pg.draw_rect_outline(360, 160, 0xFFFFFF, 450, 200);
    pg.draw_table_view(660, 160, 400, "System Log", 150);
    pg.draw_table_view(820, 160, 500, "System Log", 400);
    pg.draw_button(660, 580, false, 40, "Install", 120);
    pg.draw_button(60, 640, false, 40, "Uninstall", 120);
    pg.draw_button(220, 640, false, 40, "Update", 120);
    pg.draw_button(380, 640, false, 40, "Disable", 120);
    pg.draw_button(660, 640, false, 40, ____, 120);
    pg.draw_rect_outline(820, 680, 0xFFFFFF, 25, 300);
    pg.draw_button(1140, 680, false, 25, "Search", 100);
}
